### ISSUE TITLE
Memory fences and general improvements

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/trc#6]
Quoted from u/TDplay from this [comment](https://www.reddit.com/r/rust/comments/14plmef/comment/jqwgu8s/?utm_source=reddit&utm_medium=web2x&context=3).

## Todo
- [x] `Weak::to_trc` race condition
- [x] `Weak::clone` race condition
- [x] `impl Clone for SharedTrc`
- [x] `Support no_std` 
- [x] `Trc::cmp` documentation
- [x] Fix `Pointer` behavior 
- [x] Use different `Layout` API.
- [x] Use `ptr::drop_in_place` instead of `ptr::read`

## Quote
https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L245

Not entirely sure about this part. You seem to decrement and check the weak count, and then construct and drop a Weak (thus calling Weak::drop, which should also decrement and check the weak count).

It also seems like you only drop the data when the weak count reaches zero, which seems to defeat the point of supporting Weak pointers.

Another point is to perhaps consider using ptr::drop_in_place instead of ptr::read. It makes the intent more obvious, and it can make some optimisations more obvious to the compiler (since it doesn't need to reason about removing the copy). I think this would also allow you to support dynamically-sized types.

Trc::drop looks fine.

https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L1148

Weak::to_trc has a race condition, leading to a possible use-after-free.

Initial state: We have a SharedTrc in thread A and a Weak in thread B.

Thread B calls Weak::to_trc

Weak::to_trc checks the strong count, and reads 1

Thread A drops the SharedTrc, decrementing the strong count.

SharedTrc::drop notices that the strong count is now zero, so it deallocates the data.

Weak::to_trc increments the strong count and constructs a Trc.

The Trc is now passed to user code, which access the contents, causing a use-after-free.

To resolve this, the zero-check and the increment need to be one atomic operation, and the increment needs to not happen if the zero check fails. [fetch_update](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.fetch_update) is perfect for this. Sadly, this is slower than fetch_add, but I can't see a way to avoid it, and it seems [the standard library developers couldn't either](https://doc.rust-lang.org/1.70.0/src/alloc/sync.rs.html#2163).

https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L1191

Clone for Weak technically has a race condition: if a program clones an absurd number of Weaks in different threads, with thread being pre-empted before it can call abort, it may be possible to overflow the weak count. In practice, I don't think any real program will ever do this, and the actual likelihood of this behaviour is slim.

That's the big stuff out of the way, on to the small nitpicks:

Clone is not implemented for SharedTrc, this feels like an oversight.

You might be able to support no_std. Add this to your lib.rs:

```rust
#![cfg_attr(not(test), no_std)]

extern crate alloc;
#[cfg(feature = "force_lock")]
extern crate std;
```
It will then throw errors at every use of std. Replace these with either core or alloc.

https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L899

Documentation for Trc::cmp doesn't seem right.

https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L793

Behaviour of the Pointer formatting seems a little strange. Trc is a pointer, so it should probably print the address the Trc points to. This would also be in-line with what the standard library smart pointers do: [Arc](https://doc.rust-lang.org/src/alloc/sync.rs.html#2604), [Rc](https://doc.rust-lang.org/src/alloc/rc.rs.html#1901), [Box](https://doc.rust-lang.org/src/alloc/boxed.rs.html#1873), [&T](https://doc.rust-lang.org/src/core/fmt/mod.rs.html#2565), and [&mut T](https://doc.rust-lang.org/src/core/fmt/mod.rs.html#2572) all implement Pointer unconditionally.

https://github.com/EricLBuehler/trc/blob/89f3eb2ffec4f860b13620c82cd0f443ed6dcfeb/src/trc.rs#L1043

There is no need for the unsafe call to Layout::from_size_align_unchecked, you can just use:
```rust
Layout::new::<SharedTrcInternal<T>>()
```
If you choose to support dynamically sized types, then you can instead use:
```rust
Layout::for_value
```

**Comment by EricLBuehler** [comment]
`impl Clone for SharedTrc`: Clones do not need any special sync because they can only be created from existing objects. However, refcount bounds checking is necessary.

**Comment by EricLBuehler** [comment]
Closed as all problems are fixed.
